# Generated by Django 4.2.15 on 2025-01-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], default='candidate', max_length=10)),
                ('first_name', models.CharField(default='xyz', max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(default='xyz', max_length=50, verbose_name='Last Name')),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='masters', max_length=50, verbose_name='Add your education criteria')),
                ('experience', models.CharField(choices=[('0-1', '0-1 Years'), ('2-3', '2-3 Years'), ('4-5', '4-5 Years'), ('6-10', '6-10 Years'), ('10+', 'More than 10 Years')], default='0-1', max_length=50, verbose_name='Your work wxperience level')),
                ('has_resume', models.BooleanField(default=True, max_length=5, verbose_name='Do you have resume')),
                ('resume', models.FileField(blank=True, upload_to='profiles/', verbose_name='Upload your resume here')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('oth', 'Others')], default='', max_length=50, verbose_name='Select your gender ')),
                ('bio', models.TextField(blank=True, verbose_name='Write your bio here!')),
            ],
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50, verbose_name='Your company name')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='proImage', verbose_name='Company Image')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number')),
                ('location', models.CharField(default='New Dehli', max_length=50, verbose_name='Location ')),
                ('bio', models.TextField(blank=True, max_length=50, verbose_name='Write your bio here!!!!!!!')),
            ],
        ),
    ]
