# Generated by Django 4.2.15 on 2025-01-27 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='user_type',
        ),
    ]
