# Generated by Django 4.2.15 on 2024-12-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_candidateprofile_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Write your bio here!'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='cond_email',
            field=models.EmailField(default='', max_length=254, unique=True, verbose_name='Your Email Address'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='masters', max_length=50, verbose_name='Add your education criteria'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.CharField(choices=[('0-1', '0-1 Years'), ('2-3', '2-3 Years'), ('4-5', '4-5 Years'), ('6-10', '6-10 Years'), ('10+', 'More than 10 Years')], default='0-1', max_length=50, verbose_name='Your work wxperience level'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(default='xyz', max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female'), ('oth', 'Others')], default='', max_length=50, verbose_name='Select your gender '),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='has_resume',
            field=models.BooleanField(default=True, max_length=5, verbose_name='Do you have resume'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(default='xyz', max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, upload_to='profiles/', verbose_name='Upload your resume here'),
        ),
    ]
