# Generated by Django 5.1.5 on 2025-02-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0003_remove_candidateprofile_user_type'),
        ('JobApp', '0003_alter_job_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidate_skill', to='JobApp.skill'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, verbose_name='Write your bio here!!!!!!!'),
        ),
    ]
