# Generated by Django 4.2.15 on 2025-01-01 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0004_alter_candidateprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='recuiter_email',
            field=models.EmailField(default='abc@xyz.in', max_length=254, verbose_name='Recruiter Email Email'),
        ),
    ]
