# Generated by Django 4.2.15 on 2025-01-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0005_remove_recruiterprofile_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='cond_email',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='recuiter_email',
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='proImage', verbose_name='Company Image'),
        ),
    ]
