# Generated by Django 4.2.15 on 2025-01-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0006_remove_candidateprofile_cond_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='user_type',
            field=models.CharField(choices=[('candidate', 'Candidate'), ('recruiter', 'Recruiter')], default='candidate', max_length=10),
        ),
    ]
