# Generated by Django 4.2.15 on 2024-10-09 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recruiter_name', models.CharField(default='xyz', max_length=50, verbose_name='name')),
                ('company_name', models.CharField(max_length=50, verbose_name='Your company name')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Company Email')),
                ('contact_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone number')),
                ('bio', models.TextField(blank=True, verbose_name='Write your bio here!!!!!!!')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
