# Generated by Django 4.2.15 on 2024-10-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0002_jobmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.TextField(default='New Dehli', max_length=100, verbose_name='Location '),
        ),
    ]
