# Generated by Django 4.2.15 on 2024-10-11 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiters', '0003_recruiterprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiterprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=50, verbose_name='Write your bio here!!!!!!!'),
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(default='New Dehli', max_length=50, verbose_name='Location '),
        ),
    ]
