<<<<<<< HEAD
# Generated by Django 4.2.15 on 2024-09-17 12:26
=======
# Generated by Django 4.2.15 on 2024-09-18 10:39
>>>>>>> 96d728892f783fa2abfe3f8feb7341fa5459ca79

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CondidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
