# Generated by Django 4.2.15 on 2024-09-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CondidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='last_name')),
                ('cond_email', models.EmailField(default='', max_length=254, unique=True, verbose_name='Email-address')),
                ('cond_password', models.CharField(max_length=50, verbose_name='Condidate password')),
                ('is_condidate', models.BooleanField(default=True, max_length=50, verbose_name='is-condidate')),
                ('has_resume', models.BooleanField(default=True, max_length=5, verbose_name='has_resume')),
                ('date_applied', models.DateTimeField(auto_now_add=True, verbose_name='Date Applied')),
                ('resume', models.FileField(blank=True, upload_to='resume/', verbose_name='Resume')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('oth', 'Others')], default='', max_length=50, verbose_name='Choice ')),
                ('status', models.CharField(choices=[('apl', 'applied'), ('intw', 'intervew'), ('hrd', 'hired'), ('rjct', 'rejected')], default='apl', max_length=50, verbose_name='Status')),
                ('About', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
