# Generated by Django 4.2.15 on 2024-10-09 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('condidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50, verbose_name='job Title')),
                ('status', models.CharField(choices=[('apl', 'applied'), ('intw', 'intervew'), ('hrd', 'hired'), ('rjct', 'rejected')], default='apl', max_length=50)),
                ('applied_on', models.DateTimeField(auto_now_add=True, verbose_name='Applied DateTime')),
                ('condidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
