# Generated by Django 4.2.15 on 2024-09-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('condidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidateprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='condidateprofile',
            name='last_name',
        ),
    ]
