# Generated by Django 4.2.15 on 2024-09-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidateprofile',
            name='is_educated',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='condidateprofile',
            name='is_employed',
            field=models.BooleanField(default=False),
        ),
    ]
