# Generated by Django 4.2.15 on 2024-09-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidates', '0002_condidateprofile_is_educated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condidateprofile',
            name='firstname',
            field=models.CharField(default='Azeemkhan', max_length=100),
        ),
        migrations.AddField(
            model_name='condidateprofile',
            name='lastname',
            field=models.CharField(default='khan', max_length=50),
        ),
    ]
