# Generated by Django 4.2.15 on 2024-10-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condidates', '0002_remove_condidateprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='condidateprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='condidateprofile',
            name='first_name',
            field=models.CharField(default='xyz', max_length=50, verbose_name='first_name'),
        ),
        migrations.AddField(
            model_name='condidateprofile',
            name='last_name',
            field=models.CharField(default='xyz', max_length=50, verbose_name='last_name'),
        ),
    ]
