# Generated by Django 4.2.15 on 2025-01-15 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProxyModel',
        ),
        migrations.CreateModel(
            name='ProxyModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ProxyApp.mainmodel',),
        ),
    ]
