# Generated by Django 4.2.15 on 2025-01-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProxyApp', '0002_delete_proxymodel_proxymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmodel',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
