# Generated by Django 4.2.15 on 2025-01-25 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200, verbose_name='skill')),
            ],
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Software Developer', 'Software Developer'), ('Data Analyst', 'Data Analyst'), ('Project Manager', 'Project Manager'), ('UI/UX Designer', 'UI/UX Designer'), ('Other', 'Other')], default='Other', help_text='Title of the resume. Choose the most appropriate role.', max_length=50)),
                ('objective', models.TextField(help_text="A short paragraph about the candidate's career objectives and aspirations.", max_length=1000)),
                ('experience', models.CharField(choices=[('Entry Level', 'Entry Level (0-2 years)'), ('Mid Level', 'Mid Level (2-5 years)'), ('Senior Level', 'Senior Level (5+ years)')], default='Entry Level', help_text='Select the experience level of the candidate.', max_length=50)),
                ('education', models.CharField(choices=[('High School', 'High School'), ('Associate Degree', 'Associate Degree'), ("Bachelor's Degree", "Bachelor's Degree"), ("Master's Degree", "Master's Degree"), ('Ph.D.', 'Ph.D.')], default="Bachelor's Degree", help_text='Select the highest level of education attained.', max_length=50)),
                ('certifications', models.TextField(blank=True, help_text='Details of certifications or training. Use JSON or plain text for multiple entries.')),
                ('achievements', models.TextField(blank=True, help_text='List of notable achievements or awards. Use JSON or plain text.')),
                ('projects', models.TextField(blank=True, help_text='Summary of significant projects with details. Use JSON or plain text.')),
                ('resume_file', models.FileField(blank=True, help_text='Upload a PDF or document version of the resume.', null=True, upload_to='resumes/')),
                ('linkedin_profile', models.URLField(blank=True, help_text="URL to the candidate's LinkedIn profile.")),
                ('portfolio_website', models.URLField(blank=True, help_text="URL to the candidate's portfolio or personal website.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(default='Java', help_text='Select a key skill. Add multiple skills by creating separate entries.', max_length=255, to='JobApp.skill')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=50)),
                ('job_title', models.CharField(max_length=50, verbose_name='job Title')),
                ('status', models.CharField(choices=[('apl', 'applied'), ('intw', 'intervew'), ('hrd', 'hired'), ('rjct', 'rejected')], default='apl', max_length=50)),
                ('applied_on', models.DateTimeField(auto_now_add=True, verbose_name='Applied DateTime')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('full-time', 'Full-time'), ('part-time', 'Part-time'), ('internship', 'Internship')], max_length=50)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirements', models.TextField(help_text='List of job requirements')),
                ('experience_required', models.CharField(help_text='Required experience level', max_length=100)),
                ('specifications', models.TextField(blank=True, help_text='Any other specific requirements', null=True)),
                ('education', models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='masters', max_length=50, verbose_name='Education')),
                ('language', models.CharField(choices=[('eng', 'English Language'), ('fran', 'Franch Language'), ('urdu', 'Urdu Language')], default='eng', max_length=50, verbose_name='Languages')),
                ('schedule', models.CharField(choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift')], default='morning', max_length=50, verbose_name='Shift and schedule')),
                ('work_mode', models.CharField(choices=[('REMOTE', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('Vacancy', models.CharField(max_length=10, null=True)),
                ('passedout', models.CharField(default='2023-2024', max_length=30)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateField(default='None', max_length=20, null=True)),
                ('gender', models.CharField(blank=True, choices=[('m', 'male'), ('f', 'female')], max_length=30)),
                ('likes', models.ManyToManyField(related_name='job_likes', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(limit_choices_to={'user_type': 'recruiter'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skills', models.ManyToManyField(blank=True, related_name='technical_skill', to='JobApp.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job', to='JobApp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BookmarkJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobApp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobApp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
