# Generated by Django 4.2.15 on 2024-10-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='education',
            field=models.CharField(default='Masters', max_length=50, verbose_name='Education'),
        ),
        migrations.AddField(
            model_name='job',
            name='language',
            field=models.CharField(default='eng', max_length=50, verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='job',
            name='schedule',
            field=models.CharField(default='Morning', max_length=50, verbose_name='Shift and schedule'),
        ),
        migrations.AddField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('ONSITE', 'Onsite'), ('HYBRID', 'Hybrid')], default='ONSITE', max_length=10),
        ),
    ]
