# Generated by Django 4.2.15 on 2024-10-22 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobApp', '0002_job_education_job_language_job_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='education',
            field=models.CharField(choices=[('high_school', 'High School'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], default='masters', max_length=50, verbose_name='Education'),
        ),
        migrations.AlterField(
            model_name='job',
            name='language',
            field=models.CharField(choices=[('eng', 'English Language'), ('fran', 'Franch Language'), ('urdu', 'Urdu Language')], default='eng', max_length=50, verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='job',
            name='schedule',
            field=models.CharField(choices=[('morning', 'Morning Shift'), ('evening', 'Evening Shift')], default='morning', max_length=50, verbose_name='Shift and schedule'),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_mode',
            field=models.CharField(choices=[('REMOTE', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], default='Onsite', max_length=10),
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='JobApp.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
