# Generated by Django 4.2.15 on 2024-10-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_alter_job_education_alter_job_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='passedout',
            field=models.CharField(default='2023-2024', max_length=30),
        ),
    ]
