# Generated by Django 4.2.15 on 2025-02-27 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0003_alter_job_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
