# Generated by Django 4.2.15 on 2024-10-24 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0004_job_passedout'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='gender',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
