# Generated by Django 4.2.15 on 2025-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0004_alter_applicant_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmarkjob',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
