# Generated by Django 4.2.15 on 2024-10-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0006_alter_job_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_date',
            field=models.DateField(max_length=20, null=True),
        ),
    ]
