# Generated by Django 4.2.15 on 2024-10-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0008_bookmarkjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='end_date',
            field=models.DateField(default='2024-11-3', max_length=20, null=True),
        ),
    ]
