# Generated by Django 4.2.15 on 2024-11-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0014_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(default='Java', help_text='Select a key skill. Add multiple skills by creating separate entries.', max_length=255, to='JobApp.skill'),
        ),
    ]
