# Generated by Django 4.2.15 on 2024-11-28 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobApp', '0015_remove_resume_skills_resume_skills'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='user',
            new_name='username',
        ),
    ]
